CREATE DATABASE tripdb;
USE tripdb;
CREATE TABLE trip_exp ( id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, uid VARCHAR(1000) NOT NULL, origin VARCHAR(256) NOT NULL, destination VARCHAR(256) NOT NULL, via VARCHAR(1000), dep_time VARCHAR(1000) NOT NULL, arr_time VARCHAR(1000) NOT NULL);